version: '3.3'

services:
  app:
    build: .
    container_name: sdg_webservice
    environment:
      - MODEL_DIR=/models
      - USE_GPU=no
    volumes:
    - "../models:/models"
    ports:
    - "6007:5000"
